### ISSUE TITLE
Gamesir 3GS Support

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#835] opened 2018-04-15 18:16 UTC
As mentioned in #741 by @womble25

![51z6pld6eel _sl1024_](https://user-images.githubusercontent.com/17649707/38773640-af0055e6-4049-11e8-95e4-cd049d9e8e9c.jpg)

**Comment by mexhtown** [comment] 2018-04-15 19:54
Can you connect a gamesir control to provenance??

**Comment by jasarien** [comment] 2018-04-15 20:36
According to their website, Gamesire do not support iOS. It mentions happy chick supporting game sire controllers but doesn’t say how. https://gamesir.hk/apps/help-center#!do-gamesir-gamepads-support-iphone-ios

![5e98b4d8-29b8-4381-9fa5-4389f2395bbd](https://user-images.githubusercontent.com/104444/38783056-faf7f566-40f4-11e8-8271-4c80bff39c3b.jpeg)

**Comment by JoeMatt** [comment] 2018-04-16 15:55
might be the same protocol as Mocute's 'happy chick' second mode, it also has standard iCade. It allows more buttons and thumbsticks, but I couldn't find documentation and most of their sites are in Chinese. If someone finds some docs then It's doable I suppose. I do like my cheap mocute controller, would be nice to have the extra tiggers and joystick hooked up.

**Comment by mexhtown** [comment] 2018-04-16 17:35
I do have it working on IOS but in the happy chick app, the problem is happy chick is not supporting N64, but provenance app is but i can’t connect my gamesir control with provenance.

**Comment by womble25** [comment] 2018-04-16 19:58
I was able to press start button once on ocarina of time with the settings as a standard controller. After that it stopped working.

**Comment by mexhtown** [comment] 2018-04-16 21:27
How did you pair the gamesir control with the provenance app??

**Comment by jajajaime** [comment] 2018-04-17 00:46
When on the player controller assignment, if I press start on my GameSir G3s, it gets detected as iCade by Provenance, but still no actual actions while running the game.
The controller gets detected like a keyboard via bluetooth, and the only button that works all the time is `B`, which brings you back to the tvOS homescreen, or in some iCade controller configs, unreliably the same happens with `Select`, and with `D-pad left`.
![2018-04-16 17_45_04](https://user-images.githubusercontent.com/13631233/38842278-f141f5c2-419d-11e8-8499-1f0c5e72591c.gif)

**Comment by JoeMatt** [comment] 2018-04-17 01:30
There seems to be some real reading comprehension failures here.

Gamesir uses some variation of iCade. It's mapping to different letters. I can't find documents on what they are, nor have my own to test, so it's unsupported. You can stop leaving messages that it doens't work, we know.

**Comment by jajajaime** [comment] 2018-04-17 01:48
I wasn't complaining. Just trying to give whatever info I could gather from testing.

**Comment by jajajaime** [comment] 2018-04-17 02:44
I've also been trying to figure out how to map this gamepad on code, but not completely understanding yet how the code is structured and/or where it goes. If someone could help me with that, I could start trying to map the controller. For now, here's what I got from typing on the notes app

```
A - "delete"
B - " "
X - 
Y - "-"
D-pad Up - "\"
D-pad Right - "\"
D-pad Down - ";"
D-pad Left - "’"
R1 - ","
R2 - ""
R3 - "/"
L1 - "`"
L2 - 
L3 - "."
Start - "["
Select - "="
Clear - 
Turbo - 
R-A Up - 
R-A Right - 
R-A Down - 
R-A Left - 
L-A Up - "," (only when pushed softly)
L-A Right - 
L-A Down - 
L-A Left - ["+", "1", "—", "*", "9", "8", "\n maybe, some kind of return"] (depending on strength)
```

Maybe the notes app can't type certain chars, so for the ones that I didn't write anything, is because I didn't get anything.

**Comment by JoeMatt** [comment] 2018-04-17 02:52
You can create a new subclass of iCadeController, look at PViCade8BitdoController.m and similar, but you're still limited to the number of buttons on an MFi controller since the iCade classes just map to GameController. We'd have to add extensions to GCController to add extra buttons that standard, which wouldn't be difficult. But we want to use VirtualGameController.framework which does that already.

**Comment by womble25** [comment] 2018-04-17 09:15
I have the documentation still in the box I will have a look tonight to see any clues to how it works

**Comment by jajajaime** [comment] 2018-04-17 14:38
I was able to get a new iCade profile to load on the Apple TV last night, but whatever I did to detect a button getting pressed, I didn't get anything in-game.
Maybe I'm not understanding the iCade codes? They just mostly double in number per button, but for a keyboard none of those worked, and using the hex value of key, hex keycode, or whatever else I could think of didn't give me any results.
Maybe keyboards are not getting through once a game loads?

**Comment by jasarien** [comment] 2018-04-17 14:45
@jajajaime the output for each button you posted in an earlier comment doesn't line up with how other iCade controllers work.

For example, some 8Bitdo controllers that we support 'press' 2 keys per button, one for press down and another for release up. ie. the A button on the controller might press the `A` key for push and the `S` key for release.

If the Gamesir worked in the same way, then I'd expect to see two keypresses per button, which I don't see at all in your output.

This is the hack that iCade uses, because keyboard support in iOS is not like other OS's where key has multiple events each (as in A down, A release etc). iOS only tells the app when a key is pushed, but never when it is released, which is why iCade uses the 2 key hack.

My guess is that Gamesir controllers are not iCade controllers and that as they said on their own website, they do not support iOS. If Happy Chick supports them, then they're doing something other than iCade.

With that, I'm going to close this issue. The official word from Gamesir is that iOS is not supported, and they provide no SDK or developer documentation on how to support it, so we won't.

**Closed by jasarien** 2018-04-17 14:45 UTC
Labels: controller-related, enhancement, requires more info

**Comment by jajajaime** [comment] 2018-04-17 17:53
Makes sense. It was just worth trying it out for me, since I have the controller and I didn't want to get a new one unless it was absolutely necessary.

**Comment by JoeMatt** [comment] 2018-04-17 18:10
I might look into this at some point, I have a controller that has an iCade mode, but also a happy chick mode. I noticed to the key commands were weird, but it's supposed to work with happy chick on iOS, not sure exactly what they're doing. Gamesir has an SDK contact form, I almost submitted it but decided i was too busy to dig into it now anyway, and I'd rather see if i can figure it out myself first.

**Comment by theMaddis** [comment] 2018-05-19 22:57
Have you got any further with this. Been doing some searching and thought it may be worth contacting GameSir here: https://gamesir.hk/pages/gaming-sdk
