### ISSUE TITLE
Goole Drive save state and rom sync

### ISSUE THREAD

**Issue by frootloop88** [Provenance-Emu/Provenance#1604] opened 2021-10-01 18:03 UTC
Just like on delta. Would love this and make it usable between Apple TV and iPhone.

-------------------------------------------
<sup> 🚫 We **DO NOT** support unofficial builds installed from 3rd-party sites. ([Official Install](https://git.io/vxABg)) </sup><br><sup> ❓ **Need help or have a suggestion?** Join our [Official Discord](https://discord.gg/4TK7PU5) </sup><br>

**Comment by JoeMatt** [comment] 2021-10-13 23:10
Duplicate of #1005

**Closed by JoeMatt** 2021-10-13 23:10 UTC
Labels: request
