### ISSUE TITLE
GameCube/Wii/N64 Virtual Console Core: Dolphin

### ISSUE THREAD

**Issue by Human1895** [Provenance-Emu/Provenance#1180] opened 2019-09-04 12:35 UTC
https://github.com/dolphin-emu
https://github.com/WilliamLCobb/GC4iOS

**Comment by A-Human-Person** [comment] 2019-09-04 12:36
as a base GC4iOS is a good start

**Comment by sevdestruct** [comment] 2020-01-05 07:55
Editing…

**Comment by JoeMatt** [comment] 2020-01-06 16:53
Closing duplicate of #182 and linked project GC4iOS notes,

> Please note this is an early alpha version. Without JIT, the emulator will not be fast enough to play any games at a playable speed.

That's as of 2016, the last update that project has seen.

**Closed** 2020-01-06 16:53 UTC
Labels: core-related, request, system-GC, system-N64, system-Wii
