### ISSUE TITLE
App is crashing on iOS 15.1

### ISSUE THREAD

**Issue by PaveLGIL** [Provenance-Emu/Provenance#1624] opened 2021-10-29 16:47 UTC
App is crushing on iOS 15.1

**Comment by PaveLGIL** [comment] 2021-10-30 18:37
Sorry, i'm doing request first time.. I have updated XCode to latest version, and run build for my iPhone. Build success, but app is crushing on start. I'm running app and it closing immediately..

**Comment by JoeMatt** [comment] 2021-10-30 23:52
I don' think this is an iOS 15.1 issue since I've been using 15.x up to the current betas no problem with old and new builds.

What's the crash log?

**Comment by JoeMatt** [comment] 2021-10-30 23:57
Can't reproduce. Closing. If you have more info post it here but I suggest reading the crash logs, it may be a bad config or code signing.

**Closed by JoeMatt** 2021-10-30 23:57 UTC
Labels: bug, can't reproduce

**Comment by urherenow** [comment] 2021-10-31 00:00
First time... lol. I know what the issue is. You have to go to your phone's settings General->con and device management, and "trust" your dev certificate/trust the provenance app.

**Comment by PaveLGIL** [comment] 2021-10-31 18:57
Really sorry for my English) I'm glad I could cheer you up) After updating to MacOs Monterey and build, all working fine. IPA also working fine after AltStore update.
