### ISSUE TITLE
Screen saver activation or exiting to the home screen disables sound on some (all?) SNES games

### ISSUE THREAD

**Issue by MrTemple** [Provenance-Emu/Provenance#191] opened 2015-11-07 23:59 UTC
Playing Legend of Zelda: A Link to the Past for SNES. If the screen saver activates, or if you activate app switching, sometimes (usually with the screen saver) the game audio deactivates when you return to the game. The game is still playable, but there's no sounds (even after ROM reset). The Provenance interface sounds still work (when scrolling through the emulator's pause menu).

Often I can get it back by app-switching in/out of the program a couple times, but sometimes it requires exiting to the game library and restarting the ROM.

Not a big deal with save states, just putting it on the radar.

Thanks, and great work!

**Comment by ssstraub** [comment] 2015-11-09 16:40
I can confirm this issue. Coincidentally, it happened to me in the the same game yesterday! :)

**Comment by jasarien** [comment] 2015-11-09 16:48
Sounds like the audio session is taken over by the screensaver, but not restored when the app is reactivated. I'll take a look.

**Comment by whitverj** [comment] 2015-11-14 02:37
Happens on NES games, too.

**Comment by semicolonsnet** [comment] 2015-12-08 18:15
I've also experienced this issue when using Slide Over then switching back to the main window.

**Comment by sevdestruct** [comment] 2018-03-07 03:53
Testing this on recent swift-based builds. Cannot reproduce. Anyone still experiencing this? If not. gonna close it, since it's like.. years old.

**Comment by jasarien** [comment] 2018-04-20 15:17
@sev Slide Over is one of the multitasking modes on iPad where an app is placed above the current full screen app in an iPhone-sized window. I believe @semicolonsnet meant that they had Provenance running as the main app, and then multitasked another app on top of Provenance using the Slide Over mode.

**Comment by sevdestruct** [comment] 2018-04-20 15:32
Is that what that is called? I should go test on my iPad Pro.

**Comment by sevdestruct** [comment] 2018-04-20 17:30
Happy to report this bug is no longer with us. R.I.P. ⚰️

But I discovered a different much lesser bug, unless it's intentional, the Resume option is missing from, iPad: but resume can be accomplished from tapping outside of action sheet.

**Closed by sevdestruct** 2018-04-20 17:30 UTC
Labels: bug, can't reproduce, core-related, requires feedback

**Comment by jasarien** [comment] 2018-04-20 17:33
It's not necessarily intentional as in we purposefully left it out -- it's just how the actionsheet API works. The resume button is designated as the 'cancel' button, and the cancel button isn't shown on iPad because a popover is used to display the action sheet, and everyone knows you can tap outside a popover to dismiss it.

**Comment by sevdestruct** [comment] 2018-04-21 01:17
Well there is still a space for it though.. at least on iOS 10
