### ISSUE TITLE
2.2.0 It still does not run when you have Spanish language on the AppleTV

### ISSUE THREAD

**Issue by joakyhsf69** [Provenance-Emu/Provenance#2084] opened 2022-12-16 21:44 UTC
Since a few versions ago, if you have Apple TV in Spanish, the app does not open. If you change the language to English in the system the application opens fine.

<!--- DISCLAIMERS ---------------------------------------------------------------

🛑 STOP! Before posting, make sure you…
✅ …have checked issues for existing bug reports.
✅ …are using the latest development build (may have already been fixed).
✅ …have discussed the issue on our Discord:     https://discord.gg/4TK7PU5

🚫 We DO NOT support unofficial 3rd-party installations (buildstore, iemulators, tweakbox, etc…). 
☠️ Delete and use official install:  https://git.io/vxABg

⚠️ BUG REPORTS ONLY! If you need help, use Discord. If suggesting a feature, use the request form. 
🚦 If you have read the above, please continue…
❌ Reports that do not use the template below will be closed and locked immediately.

**Comment by JoeMatt** [comment] 2022-12-18 06:42
duplicate of #2073

**Closed by JoeMatt** 2022-12-18 06:42 UTC
Labels: bug
