### ISSUE TITLE
Version 2.0.0 doesn’t build, missing files

### ISSUE THREAD

**Issue by tracicot** [Provenance-Emu/Provenance#1565] opened 2021-08-16 09:16 UTC
When downloading the 2.0.0 zip and attempting to build, failure occurs because `Cores/Reicast/reicast-emulator` folder is empty. (Needs `core/deps/libzip/zip_unchange_data.c` before build aborts). Also tried cloning and checking out tag 2.0.0 but same issue.

**Comment by urherenow** [comment] 2021-08-16 14:50
This is 100% your fault. Not a bug for github. You can't "download a zip" of a project that has external dependancies. You must clone --recursive.

Following the installation instructions tells you how to build it.

**Comment by JoeMatt** [comment] 2021-08-16 16:19
what he said. closing.

**Closed by JoeMatt** 2021-08-16 16:19 UTC

**Comment by tracicot** [comment] 2021-08-16 20:14
Ah, thank you. I overlooked those flags in the docs.
