### ISSUE TITLE
MFi Menu Button + Game Info while playing bugs

### ISSUE THREAD

**Issue by sevdestruct** [Provenance-Emu/Provenance#758] opened 2018-03-14 08:04 UTC
- [x] 1. If you pause a game with MFi Controller connected and select Game Info and then Done the MFi Menu Button will no longer work (other inputs seems to though - but haven't confiremd all inputs)
- [x] 2. If you hit Menu Button while Game Info is slid over game, the game will unpause in the background, and again the MFi Menu Button will stop working.

Additionally, I think the expected behavior for the MFi Menu Button here would be to dismiss the Game Info slide over view.

- [x] Dismiss Game Info with MFi Menu Button

<sub>Tested on iOS 11, iPhone X, GameVice MFi Controller, SNES9x core…</sub><br>

**Comment by CooperRS** [comment] 2018-04-01 07:57
After some testing, I can confirm that the same same bugs also apply for the tvOS version (no surprise as the code is shared, I think).

I think on tvOS an option is to present the Game Info Controller without a wrapping UINavigationController (just like when presenting the Game Info Controller for the library). Pressing the menu button will then dismiss the Game Info Controller. However, after dismissing the Game Info one would need to either resume the game or represent the pause menu (neither is done automatically).

Unfortunately, I don't know how to fix the scenario on iOS. Presenting the Game Info Controller there without a UINavigationController might lock the user because the menu button is not always available.

What do you think? Ready to write a PR when there is an idea how to fix the iOS scenario 🙂.

**Comment by jasarien** [comment] 2018-04-01 09:04
I think I fixed this in the latest develop last night.

**Comment by DarkRedFish** [comment] 2018-04-04 12:55
I can confirm I'm not able to reproduce this bug from develop

**Comment by jasarien** [comment] 2018-04-04 14:06
Marking this as fixed

**Comment by sevdestruct** [comment] 2018-04-06 04:30
Thanks, @jasarien. good work.

**Comment by sevdestruct** [comment] 2018-04-06 04:59
Reviewing this and I noticed Menu button now flips artwork over before dismissing the view, is that intentional?

**Comment by jasarien** [comment] 2018-04-06 07:39
Probably not. Can’t think why it might do that — I’ll take a look when I get a spare moment.

**Comment by JoeMatt** [comment] 2018-04-18 05:34
Such a minor bug remaining, closing this, can fix the flip artwork in redesign

**Closed by JoeMatt** 2018-04-18 05:34 UTC
Labels: bug, confirmed-bug, confirmed-fix, controller-related, dev, dev-branch, unexpected-behavior
